services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8.13
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8011:8080
    networks:
      - personal_network

networks:
  personal_network:
    external: true
