services:
  beszel:
    image: henrygd/beszel:0.12.9
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8005:8090
    volumes:
      - beszel_data:/beszel_data
      - beszel_socket:/beszel_socket
    networks:
      - personal_network

  beszel-agent:
    image: henrygd/beszel-agent:0.12.9
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - beszel_agent_data:/var/lib/beszel-agent
      - beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:8005
    env_file:
      - .env

volumes:
  beszel_data:
  beszel_socket:
  beszel_agent_data:

networks:
  personal_network:
    external: true
