services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.0.0
    volumes:
      - immich-filen:/data
      - immich-thumbnail:/data/thumbs
      - immich-video:/data/encoded-video
      - immich-library:/data/library
      - immich-profile:/data/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "8009:2283"
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "test -r /data/upload && /usr/src/app/server/bin/immich-healthcheck",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 45s
    networks:
      - personal_network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v2.0.0
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "/usr/src/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - personal_network

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - personal_network

volumes:
  model-cache:
  immich-thumbnail:
  immich-video:
  immich-library:
  immich-profile:
  immich-filen:
    driver: rclone
    driver_opts:
      type: "webdav"
      webdav_url: "http://localhost:4001"
      webdav_vendor: "other"
      webdav_user: "admin"
      webdav_pass: "LACyVhZAkys-312NHJJrUobWhYky"
      allow_other: "true"
      path: "personal-server/immich/uploads"
      vfs_cache_mode: "writes"
      poll_interval: "30s"

networks:
  personal_network:
    external: true
