packages:
  - apps/*
  - packages/*

catalogs:
  core:
    "@dotenvx/dotenvx": ^1.49.0
    "@t3-oss/env-core": ^0.13.8
    typescript: ^5.9.2

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - better-sqlite3
  - oxc-resolver
