packages:
  - apps/*
  - packages/*

catalogs:
  core:
    '@dotenvx/dotenvx': ^1.49.0
    ai: ^5.0.22
    ai-fallback: ^1.0.2
    typescript: ^5.9.2
    zod: ^4.1.1

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - oxc-resolver
