services:
  activepieces:
    image: activepieces/activepieces:0.68.3
    container_name: activepieces
    restart: unless-stopped
    ports:
      - '8006:80'
    depends_on:
      - ap_redis
    environment:
      AP_DB_TYPE: POSTGRES
      AP_QUEUE_MODE: REDIS
      AP_POSTGRES_DATABASE: activepieces
      AP_POSTGRES_HOST: postgres_main
      AP_POSTGRES_USERNAME: postgres
      AP_POSTGRES_PASSWORD: postgres
      AP_POSTGRES_PORT: 5432
      AP_REDIS_TYPE: DEFAULT
      AP_REDIS_HOST: ap_redis
      AP_REDIS_PORT: 6379
      AP_EXECUTION_MODE: UNSANDBOXED
      AP_FRONTEND_URL: "http://personal-01:8006"
    volumes:
      - ap_cache:/usr/src/app/cache
    env_file:
      - .env
    networks:
      - personal_network
    deploy:
      resources:
        reservations:
          memory: 768m
        limits:
          memory: 1024m

  ap_redis:
    image: redis:7.4.5-bookworm
    container_name: ap_redis
    restart: unless-stopped
    volumes:
      - ap_redis_data:/data
    networks:
      - personal_network

volumes:
  ap_cache:
  ap_redis_data:

networks:
  personal_network:
    external: true
