name: lobe-chat-database
services:
# version lock ref: https://github.com/lobehub/lobe-chat/pull/7331
  casdoor:
    image: casbin/casdoor:v2.13.0
    container_name: lobe-casdoor
    ports:
      - 8007:8000
    entrypoint: /bin/sh -c './server --createDatabase=true'
    environment:
      httpport: 8000
      RUNNING_IN_DOCKER: 'true'
      driverName: 'postgres'
      dataSourceName: 'user=postgres password=postgres host=postgres_main port=5432 sslmode=disable dbname=casdoor'
      runmode: 'dev'
    volumes:
      - ./init_data.json:/init_data.json
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - personal_network
    extra_hosts:
      - "personal-01:host-gateway"

  lobe:
    image: lobehub/lobe-chat-database:1.127.0
    container_name: lobe-chat
    ports:
      - 8008:3210
    depends_on:
      - casdoor
    environment:
      NEXT_AUTH_SSO_PROVIDERS: casdoor
      NEXTAUTH_URL: http://personal-01:8008/api/auth
      DATABASE_URL: postgresql://postgres:postgres@postgres_main:5432/lobe
      LLM_VISION_IMAGE_USE_BASE64: 1
      FEATURE_FLAGS: "-check_updates,-welcome_suggest"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - personal_network
    extra_hosts:
      - "personal-01:host-gateway"
    entrypoint: >
      /bin/sh -c "
        /bin/node /app/startServer.js &
        LOBE_PID=\$!
        sleep 3
        if [ $(wget --timeout=5 --spider --server-response ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -c 'HTTP/1.1 200 OK') -eq 0 ]; then
          echo '⚠️Warning: Unable to fetch OIDC configuration from Casdoor'
          echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
          echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
        else
          if ! wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep 'issuer' | grep ${AUTH_CASDOOR_ISSUER}; then
            printf '❌Error: The Auth issuer is conflict, Issuer in OIDC configuration is: %s' \$(wget -O - --timeout=5 ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration 2>&1 | grep -E 'issuer.*' | awk -F '\"' '{print \$4}')
            echo ' , but the issuer in .env file is: ${AUTH_CASDOOR_ISSUER} '
            echo 'Request URL: ${AUTH_CASDOOR_ISSUER}/.well-known/openid-configuration'
            echo 'Read more at: https://lobehub.com/docs/self-hosting/server-database/docker-compose#necessary-configuration'
          fi
        fi
        wait \$LOBE_PID
      "

networks:
  personal_network:
    external: true
