services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.7.6
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - ALLOW_INTERNAL_REQUESTS=true
    volumes:
      - heimdall:/config
    ports:
      - 8012:80
      # - 443:443
    restart: unless-stopped
    networks:
      - personal_network

volumes:
  heimdall:

networks:
  personal_network:
    external: true
