services:
  kavita:
    image: jvmilazz0/kavita:0.8.7
    container_name: kavita
    volumes:
      - kavita_config:/kavita/config
      - /root/filen-sync/kavita_lib:/libraries
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8004:5000"
    restart: unless-stopped
    networks:
      - personal_network

  kavita_backup:
    image: offen/docker-volume-backup:v2
    container_name: kavita_backup
    restart: unless-stopped
    environment:
      BACKUP_RETENTION_DAYS: '7'
    volumes:
      - kavita_config:/backup/kavita_config:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/filen-sync/kavita_backup:/archive
    networks:
      - personal_network

volumes:
  kavita_config:

networks:
  personal_network:
    external: true
