services:
  obsidian_couchdb:
    image: couchdb:3.5.0
    container_name: obsidian_couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    volumes:
      - couchdb_data:/opt/couchdb/data
      - couchdb_etc:/opt/couchdb/etc/local.d
    ports:
      - 5984:5984
    restart: unless-stopped
    networks:
      - personal_network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535


  obsidian_couchdb_backup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obsidian_couchdb_backup
    depends_on:
      - obsidian_couchdb
    volumes:
      - /root/filen-sync/couchdb_backup:/backup
    environment:
      TZ: Asia/Jakarta
      COUCH_URL: http://admin:admin@obsidian_couchdb:5984
      COUCH_DATABASE: obsidiannotes
      CLEANUP_DAYS: 7
    restart: unless-stopped
    networks:
      - personal_network

volumes:
  couchdb_data:
  couchdb_etc:

networks:
  personal_network:
    external: true